plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "D:\\DAI-Career-OS\\smart-river-surveillance"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]